### ISSUE TITLE
Reco does not work for some raw files 

### ISSUE THREAD

**Issue by JeremieMerlin** [bdorney/CMS_GEM_Analysis_Framework#4]
Running the framework in Reco mode on GE11-VII-S-CERN-0001 , Run 40-58

The config file for Run040 is available at : /afs/cern.ch/user/j/jmerlin/public/SliceTest_QC5_Data/Reco_Bug_Report/
The Run040 raw file is available at : /afs/cern.ch/user/j/jmerlin/public/SliceTest_QC5_Data/Reco_Bug_Report/
 Using maaping file : Mapping_GE11-VII-S.cfg

Using the command :
> ./frameworkMain config/configRun_RunNo40.cfg true

Terminal output : 

[jmerlin@lxplus136 CMS_GEM_Analysis_Framework]$ ./frameworkMain config/configRun_RunNo40.cfg true
ParameterLoader::setFileStream() - trying to open and read: config/configRun_RunNo40.cfg
ParameterLoaderRun::loadParametersRun() - Found Run Heading
ParameterLoaderRun::loadParametersRun(): End of run info header reached!
ParameterLoader::getPairedRunList(): End of run list header reached!
ParameterLoader::getPairedRunList(): The following runs will be analyzed:
	Run40	../CMSGEM/Data/GE11-VII-L-CERN-0001/GE11-VII-L-CERN-0001_Run040_Physics_RandomTrigger_588uA_XRay40kV99uA_118kEvt.raw
rSetup.strRunMode = ONLY_RECONSTRUCTION
SRSConfiguration: Init conf file not specified. Setting defaults.
  SRSConfiguration::Load() ==> Loading cfg from config/configReco.cfg
  SRSConfiguration::Load() ==> RUNTYPE               ROOTFILE
  SRSConfiguration::Load() ==> RUNNAME               data
  SRSConfiguration::Load() ==> CYCLEWAIT             2
  SRSConfiguration::Load() ==> ZEROSUPCUT            10
  SRSConfiguration::Load() ==> MINCLUSTSIZE          1
  SRSConfiguration::Load() ==> MAXCLUSTSIZE          20
  SRSConfiguration::Load() ==> MAXCLUSTMULT          20
  SRSConfiguration::Load() ==> HISTCFG               ../../configFileDir/histogram.cfg
  SRSConfiguration::Load() ==> DISPCFG               ../../configFileDir/display.cfg
  SRSConfiguration::Load() ==> MAPFILE               config/Mapping_GE11-VII-S.cfg
  SRSConfiguration::Load() ==> PADMAPFILE            ../../configFileDir/padMapping.cfg
  SRSConfiguration::Load() ==> SAVEDMAPFILE          ../../results/savedMapping.cfg
  SRSConfiguration::Load() ==> PEDFILE               ../../pedestalDir/pedestal.root
  SRSConfiguration::Load() ==> RAWPEDFILE            ../../pedestalDir/rawpedestal.root
  SRSConfiguration::Load() ==> CLUSTERPOSCORRFILE    ../../pedestalDir/clusterPositionCorrection.root
  SRSConfiguration::Load() ==> CLUSTERPOSCORRFLAG    NO
  SRSConfiguration::Load() ==> HIT_ADCS              signalPeak
  SRSConfiguration::Load() ==> CLUSTER_ADCS          totalADCs
  SRSConfiguration::Load() ==> STARTEVENTNUMBER      0
  SRSConfiguration::Load() ==> EVENTFREQUENCYNUMBER  1
  SRSConfiguration::Load() ==> APVGAINCALIB          
  SRSConfiguration::Load() ==> ROOTDATATYPE          HITS_AND_CLUSTERS
  SRSConfiguration::Load() ==> OFFSETDIR             ../../offsetDir/
  SRSMapping::Clear() ==> Clearing Previous Mapping 
  SRSMapping::Clear() ==> Previous Mapping cleared 
  SRSMapping::LoadDefaultMapping() ==> Loading Mapping from config/Mapping_GE11-VII-S.cfg 
 Readout Mapping for CMSGEM : 0
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=0, EtaSector=CMSSECTOR1, etaSectorSize=390.006012, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 1
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=1, EtaSector=CMSSECTOR2, etaSectorSize=360.343994, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 2
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=2, EtaSector=CMSSECTOR3, etaSectorSize=335.295990, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 3
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=3, EtaSector=CMSSECTOR4, etaSectorSize=310.247009, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 4
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=4, EtaSector=CMSSECTOR5, etaSectorSize=288.927002, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 5
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=5, EtaSector=CMSSECTOR6, etaSectorSize=267.606995, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 6
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=6, EtaSector=CMSSECTOR7, etaSectorSize=249.395996, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1
 Readout Mapping for CMSGEM : 7
   SRSMapping::SetDetectorMap() =>readout=CMSGEM, detType=CMSGEM, det=CMS, detID=7, EtaSector=CMSSECTOR8, etaSectorSize=231.186005, nbOSectorfConnectors=3.000000, apvOrientOnEtaSector=1

  ======================================================================================================================
  ======================================================================================================================
  SRSMapping::PrintMapping() ==> Detector = CMS 
  SRSMapping::PrintMapping()     Plane = CMSSECTOR1,        FEC = 1 
  SRSMapping::PrintMapping() ==> adcCh=2,  apvName=apv14_Id18_CMSSECTOR1_adcCh2_FecId1,  apvID=18, apvNo=14,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=8,  apvName=apv20_Id24_CMSSECTOR1_adcCh8_FecId1,  apvID=24, apvNo=20,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=9,  apvName=apv21_Id25_CMSSECTOR1_adcCh9_FecId1,  apvID=25, apvNo=21,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR2,        FEC = 1 
  SRSMapping::PrintMapping() ==> adcCh=3,  apvName=apv15_Id19_CMSSECTOR2_adcCh3_FecId1,  apvID=19, apvNo=15,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=6,  apvName=apv18_Id22_CMSSECTOR2_adcCh6_FecId1,  apvID=22, apvNo=18,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=7,  apvName=apv19_Id23_CMSSECTOR2_adcCh7_FecId1,  apvID=23, apvNo=19,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR3,        FEC = 1 
  SRSMapping::PrintMapping() ==> adcCh=0,  apvName=apv12_Id16_CMSSECTOR3_adcCh0_FecId1,  apvID=16, apvNo=12,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=4,  apvName=apv16_Id20_CMSSECTOR3_adcCh4_FecId1,  apvID=20, apvNo=16,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=5,  apvName=apv17_Id21_CMSSECTOR3_adcCh5_FecId1,  apvID=21, apvNo=17,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR4,        FEC = 1 
  SRSMapping::PrintMapping() ==> adcCh=1,  apvName=apv13_Id17_CMSSECTOR4_adcCh1_FecId1,  apvID=17, apvNo=13,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=10,  apvName=apv22_Id26_CMSSECTOR4_adcCh10_FecId1,  apvID=26, apvNo=22,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=11,  apvName=apv23_Id27_CMSSECTOR4_adcCh11_FecId1,  apvID=27, apvNo=23,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR5,        FEC = 2 
  SRSMapping::PrintMapping() ==> adcCh=5,  apvName=apv5_Id37_CMSSECTOR5_adcCh5_FecId2,  apvID=37, apvNo=5,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=12,  apvName=apv10_Id44_CMSSECTOR5_adcCh12_FecId2,  apvID=44, apvNo=10,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=13,  apvName=apv11_Id45_CMSSECTOR5_adcCh13_FecId2,  apvID=45, apvNo=11,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR6,        FEC = 2 
  SRSMapping::PrintMapping() ==> adcCh=4,  apvName=apv4_Id36_CMSSECTOR6_adcCh4_FecId2,  apvID=36, apvNo=4,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=8,  apvName=apv6_Id40_CMSSECTOR6_adcCh8_FecId2,  apvID=40, apvNo=6,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=9,  apvName=apv7_Id41_CMSSECTOR6_adcCh9_FecId2,  apvID=41, apvNo=7,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR7,        FEC = 2 
  SRSMapping::PrintMapping() ==> adcCh=3,  apvName=apv3_Id35_CMSSECTOR7_adcCh3_FecId2,  apvID=35, apvNo=3,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=10,  apvName=apv8_Id42_CMSSECTOR7_adcCh10_FecId2,  apvID=42, apvNo=8,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=11,  apvName=apv9_Id43_CMSSECTOR7_adcCh11_FecId2,  apvID=43, apvNo=9,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 

  SRSMapping::PrintMapping()     Plane = CMSSECTOR8,        FEC = 2 
  SRSMapping::PrintMapping() ==> adcCh=0,  apvName=apv0_Id32_CMSSECTOR8_adcCh0_FecId2,  apvID=32, apvNo=0,  apvIndex=2,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=1,  apvName=apv1_Id33_CMSSECTOR8_adcCh1_FecId2,  apvID=33, apvNo=1,  apvIndex=0,  apvOrientation=0,  apvHdr=1300 
  SRSMapping::PrintMapping() ==> adcCh=2,  apvName=apv2_Id34_CMSSECTOR8_adcCh2_FecId2,  apvID=34, apvNo=2,  apvIndex=1,  apvOrientation=0,  apvHdr=1300 

======================================================================================================================
  SRSMapping::PrintMapping() ==> Mapping of 1 detectors, 8 planes, 2 FECs, 24 APVs
======================================================================================================================
  SRSOutputROOT::InitRootFile() ==> Creating the Hit Tree: fHitTree 
  SRSOutputROOT::InitRootFile() ==> Initialising the branches for fHitTree 
  SRSOutputROOT::InitRootFile() ==> Creating the Cluster Tree: fClusterTree 
  SRSOutputROOT::InitRootFile() ==> Initialising the branches for fClusterTree 
 +++ reprocess: Number of long words on this event exceed the maximum 5000 please change nMax
	SRSOutputROOT::WriteRootFile() ==> Init Root file ../CMSGEM/Data/GE11-VII-L-CERN-0001/GE11-VII-L-CERN-0001_Run040_Physics_RandomTrigger_588uA_XRay40kV99uA_118kEvt_dataTree.root 
  SRSMapping::Clear() ==> Clearing Previous Mapping 
  SRSMapping::Clear() ==> Previous Mapping cleared 

apparently the framework is not entering in the reconstruction loop. It seems to quit because of the number of long words in events that exceed the limit.

This problem is also present for other runs of the same measurement campaign.

**Comment by bdorney** [comment]
Issue was traced to grid files (e.g. config/configRun_RunNoX.cfg, corresponding script, and corresponding stdout, log, and err files) not being removed between calls of scripts/runMode_Grid*.sh 

Calling scripts/cleanGridFiles.sh between calls to scripts/runMode_Grid*.sh should resolve future issues.
