### ISSUE TITLE
Save files as .eps and .C

### ISSUE THREAD

**Issue by jsturdy** [bdorney/CMS_GEM_Analysis_Framework#8]
Saving files as [```.eps``` and ```.C```](https://github.com/bdorney/CMS_GEM_Analysis_Framework/blob/release_v3.1/src/PlotterGeneric.cpp#L264-L265) makes it very simple to do after-the-fact changes to style, without re-running any additional code

**Comment by bdorney** [comment]
@jsturdy If you fork the develop branch and make a feature branch you can add *.eps and *.C files to be produced on the output by modifying "PlotterGeneric::save2ImgFile()" which is coded in src/PlotterGeneric.cpp lines 274-282.

Then I can merge it back into the develop branch

**Comment by bdorney** [comment]
Functionality has been added in commit:

[develop 548f521] adding functionality for .C and .eps files to PlotterGeneric

See develop branch or pending release_v4.0 branch
